ARG ENV
ARG TIMEZONE

FROM php:7.4.10-fpm-buster
RUN apt-get update
RUN apt-get install -y \
    apt-utils \
    ca-certificates \
    apt-transport-https \
    software-properties-common \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    unzip \
    postgresql-server-dev-11

COPY config/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN docker-php-ext-install \
    intl \
    pdo_pgsql \
    zip \
    opcache

ARG ENV

RUN if [ "$ENV" = "dev" ] ; then \
        pecl install xdebug-3.0.4 && \
        docker-php-ext-enable xdebug  \
    ; fi

COPY config/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
COPY config/docker-php-memlimit.ini /usr/local/etc/php/conf.d/docker-php-memlimit.ini

RUN curl -sS https://getcomposer.org/installer | php -- \
--install-dir=/usr/bin --filename=composer && chmod +x /usr/bin/composer

ARG TIMEZONE

RUN ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone

WORKDIR /var/www/app

RUN usermod -u 1000 www-data